---
name: configure

on:
  workflow_dispatch:
  schedule:
    # Daily at 12:12pm.
    - cron: "12 12 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/config/*"
      - ".github/workflows/configure.yaml"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
      - run: ".github/config/configure.sh"
        env:
          GITHUB_TOKEN: "${{ secrets.CONFIGURE_REPOS_TOKEN }}"
