---
name: configure

on:
  workflow_dispatch:
  schedule:
    # Daily at 12:12pm.
    - cron: "12 12 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/config/*"
      - ".github/workflows/configure.yaml"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # pin@v3
      - run: ".github/config/configure.sh"
        env:
          GITHUB_TOKEN: "${{ secrets.CONFIGURE_REPOS_TOKEN }}"
